spring.application.name=supra-banking
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/supra_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

app.security.jwt.secret=${JWT_SECRET:c3VwcmEtYmFua2luZy1kZXZlbG9wbWVudC1zZWNyZXQtMjAyNi1zdXByYS1iYW5raW5nLWFwcA==}
app.security.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

app.security.admin.username=${ADMIN_USERNAME:admin}
app.security.admin.email=${ADMIN_EMAIL:admin@supra-banking.local}
app.security.admin.password=${ADMIN_PASSWORD:Admin123!}

